sudo: required
services:
  - docker

before_install:
  - docker build -t vikas-kumar56/docker-react -f Dockerfile.dev .

script:
  - docker run vikas-kumar56/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: "docker-react-vapp"
